from datetime import datetime
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query, status
from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy import desc

from api.deps import db_dependency, get_current_user, require_admin_or_staff
from api.models import Category, Product, ProductImage, ProductVariant

router = APIRouter(tags=["product-images"])

images_router = APIRouter(prefix="/products/{product_id}/images")
search_router = APIRouter(prefix="/products")


# ── Schemas ──────────────────────────────────────────────────────────────────


class ProductImageRead(BaseModel):
    image_id: UUID
    product_id: UUID
    variant_id: Optional[UUID] = None
    image_url: str
    is_primary: bool
    has_embedding: bool = False
    created_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class ProductImageCreate(BaseModel):
    variant_id: Optional[UUID] = None
    image_url: str
    is_primary: bool = False
    embedding: Optional[list[float]] = Field(
        None, description="512-dimensional vector embedding for visual search"
    )


class ProductImageUpdate(BaseModel):
    variant_id: Optional[UUID] = None
    image_url: Optional[str] = None
    is_primary: Optional[bool] = None
    embedding: Optional[list[float]] = None


class VisualSearchRequest(BaseModel):
    embedding: list[float] = Field(
        ..., description="512-dimensional query vector generated by CLIP/multimodal model"
    )
    top_k: int = Field(10, ge=1, le=50)
    min_similarity: float = Field(0.0, ge=0.0, le=1.0)
    category_id: Optional[UUID] = None


class VisualSearchResultItem(BaseModel):
    product_id: UUID
    product_name: str
    product_description: Optional[str] = None
    matched_image_id: UUID
    matched_image_url: str
    variant_id: Optional[UUID] = None
    variant_model: Optional[str] = None
    variant_color: Optional[str] = None
    variant_price: Optional[float] = None
    similarity_score: float

    model_config = ConfigDict(from_attributes=True)


# ── Helpers ──────────────────────────────────────────────────────────────────


def _image_to_read(img: ProductImage) -> ProductImageRead:
    return ProductImageRead(
        image_id=img.image_id,
        product_id=img.product_id,
        variant_id=img.variant_id,
        image_url=img.image_url,
        is_primary=img.is_primary,
        has_embedding=img.embedding is not None,
        created_at=img.created_at,
    )


def _ensure_single_primary(db, product_id: UUID, exclude_image_id: Optional[UUID] = None):
    query = db.query(ProductImage).filter(
        ProductImage.product_id == product_id,
        ProductImage.is_primary == True,
    )
    if exclude_image_id:
        query = query.filter(ProductImage.image_id != exclude_image_id)
    for img in query.all():
        img.is_primary = False


# ── Product Images CRUD Endpoints ────────────────────────────────────────────


@images_router.get("", response_model=list[ProductImageRead])
def list_product_images(
    product_id: UUID,
    db: db_dependency,
    _: dict = Depends(get_current_user),
    variant_id: Optional[UUID] = Query(None),
):
    """List images for a product, optionally filtered by variant."""
    if not db.query(Product).filter(Product.product_id == product_id).first():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")

    query = db.query(ProductImage).filter(ProductImage.product_id == product_id)
    if variant_id is not None:
        query = query.filter(ProductImage.variant_id == variant_id)

    images = query.order_by(ProductImage.is_primary.desc(), ProductImage.created_at.asc()).all()
    return [_image_to_read(img) for img in images]


@images_router.get("/{image_id}", response_model=ProductImageRead)
def get_product_image(
    product_id: UUID,
    image_id: UUID,
    db: db_dependency,
    _: dict = Depends(get_current_user),
):
    """Get single product image."""
    img = (
        db.query(ProductImage)
        .filter(ProductImage.product_id == product_id, ProductImage.image_id == image_id)
        .first()
    )
    if not img:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product image not found")
    return _image_to_read(img)


@images_router.post("", response_model=ProductImageRead, status_code=status.HTTP_201_CREATED)
def create_product_image(
    product_id: UUID,
    body: ProductImageCreate,
    db: db_dependency,
    _: dict = Depends(require_admin_or_staff),
):
    """Admin/Staff: Add an image with optional vector embedding to product/variant."""
    if not db.query(Product).filter(Product.product_id == product_id).first():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product not found")

    if body.variant_id is not None:
        variant = (
            db.query(ProductVariant)
            .filter(
                ProductVariant.variant_id == body.variant_id,
                ProductVariant.product_id == product_id,
            )
            .first()
        )
        if not variant:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Variant not found for this product",
            )

    if body.is_primary:
        _ensure_single_primary(db, product_id)

    img = ProductImage(
        product_id=product_id,
        variant_id=body.variant_id,
        image_url=body.image_url,
        is_primary=body.is_primary,
        embedding=body.embedding,
    )
    db.add(img)
    db.commit()
    db.refresh(img)
    return _image_to_read(img)


@images_router.put("/{image_id}", response_model=ProductImageRead)
def update_product_image(
    product_id: UUID,
    image_id: UUID,
    body: ProductImageUpdate,
    db: db_dependency,
    _: dict = Depends(require_admin_or_staff),
):
    """Admin/Staff: Update image metadata or embedding."""
    img = (
        db.query(ProductImage)
        .filter(ProductImage.product_id == product_id, ProductImage.image_id == image_id)
        .first()
    )
    if not img:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product image not found")

    if body.variant_id is not None:
        variant = (
            db.query(ProductVariant)
            .filter(
                ProductVariant.variant_id == body.variant_id,
                ProductVariant.product_id == product_id,
            )
            .first()
        )
        if not variant:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Variant not found for this product",
            )
        img.variant_id = body.variant_id

    if body.is_primary is True:
        _ensure_single_primary(db, product_id, exclude_image_id=image_id)
        img.is_primary = True
    elif body.is_primary is False:
        img.is_primary = False

    if body.image_url is not None:
        img.image_url = body.image_url
    if body.embedding is not None:
        img.embedding = body.embedding

    db.commit()
    db.refresh(img)
    return _image_to_read(img)


@images_router.delete("/{image_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_product_image(
    product_id: UUID,
    image_id: UUID,
    db: db_dependency,
    _: dict = Depends(require_admin_or_staff),
):
    """Admin/Staff: Delete product image."""
    img = (
        db.query(ProductImage)
        .filter(ProductImage.product_id == product_id, ProductImage.image_id == image_id)
        .first()
    )
    if not img:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Product image not found")
    db.delete(img)
    db.commit()


# ── Visual Search Endpoint ───────────────────────────────────────────────────


@search_router.post("/search-by-image", response_model=list[VisualSearchResultItem])
def search_products_by_image(
    body: VisualSearchRequest,
    db: db_dependency,
    _: dict = Depends(get_current_user),
):
    """
    Visual Search: Find similar products using image embedding & pgvector cosine distance.
    The client or frontend uploads/encodes the image vector (512-dim) and passes it here.
    """
    # Cosine distance operator in pgvector: <=>
    # Cosine similarity = 1 - cosine_distance
    distance_expr = ProductImage.embedding.cosine_distance(body.embedding)
    similarity_expr = 1 - distance_expr

    query = (
        db.query(
            ProductImage,
            Product,
            ProductVariant,
            similarity_expr.label("similarity"),
        )
        .join(Product, ProductImage.product_id == Product.product_id)
        .outerjoin(ProductVariant, ProductImage.variant_id == ProductVariant.variant_id)
        .filter(ProductImage.embedding.isnot(None))
    )

    if body.category_id is not None:
        query = query.join(Product.categories).filter(Category.category_id == body.category_id)

    # Order by similarity descending (distance ascending)
    results = query.order_by(distance_expr.asc()).limit(body.top_k * 2).all()

    # Deduplicate by product_id if desired, or return top variant matches
    seen_products = set()
    output: list[VisualSearchResultItem] = []

    for img, prod, var, sim in results:
        sim_val = float(sim) if sim is not None else 0.0
        if sim_val < body.min_similarity:
            continue

        if prod.product_id in seen_products:
            continue
        seen_products.add(prod.product_id)

        output.append(
            VisualSearchResultItem(
                product_id=prod.product_id,
                product_name=prod.name,
                product_description=prod.description,
                matched_image_id=img.image_id,
                matched_image_url=img.image_url,
                variant_id=var.variant_id if var else None,
                variant_model=var.model if var else None,
                variant_color=var.color if var else None,
                variant_price=float(var.price) if var and var.price else None,
                similarity_score=round(sim_val, 4),
            )
        )

        if len(output) >= body.top_k:
            break

    return output


router.include_router(images_router)
router.include_router(search_router)
